import type { LucideIcon } from "lucide-react";
import {
  Building2,
  Home,
  Sun,
  Plane,
  MapPin,
  Shield,
  Waves,
  Tag,
  Store,
  UtensilsCrossed,
  Car,
  Ship,
  Train,
  Bus,
  Tent,
  TreePine,
  Hotel,
  Landmark,
  Briefcase,
  GraduationCap,
  Heart,
  Stethoscope,
  Gem,
  ShoppingBag,
  Music,
  Camera,
  Mountain,
  Sailboat,
  Warehouse,
  Dumbbell,
  Sparkles,
} from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  Building2,
  Home,
  Sun,
  Plane,
  MapPin,
  Shield,
  Waves,
  Tag,
  Store,
  UtensilsCrossed,
  Car,
  Ship,
  Train,
  Bus,
  Tent,
  TreePine,
  Hotel,
  Landmark,
  Briefcase,
  GraduationCap,
  Heart,
  Stethoscope,
  Gem,
  ShoppingBag,
  Music,
  Camera,
  Mountain,
  Sailboat,
  Warehouse,
  Dumbbell,
  Sparkles,
};

export const AVAILABLE_ICONS = [
  { name: "Building2", label: "Edifício / Hotel" },
  { name: "Home", label: "Casa / Pousada" },
  { name: "Sun", label: "Sol / Resort" },
  { name: "Plane", label: "Avião / Operadora" },
  { name: "MapPin", label: "Mapa / Receptivo" },
  { name: "Shield", label: "Escudo / Seguro" },
  { name: "Waves", label: "Ondas / Parque Aquático" },
  { name: "Hotel", label: "Hotel" },
  { name: "Store", label: "Loja" },
  { name: "UtensilsCrossed", label: "Restaurante" },
  { name: "Car", label: "Carro / Transporte" },
  { name: "Ship", label: "Navio / Cruzeiro" },
  { name: "Train", label: "Trem" },
  { name: "Bus", label: "Ônibus" },
  { name: "Tent", label: "Acampamento" },
  { name: "TreePine", label: "Natureza / Eco" },
  { name: "Landmark", label: "Marco / Turismo" },
  { name: "Briefcase", label: "Empresa" },
  { name: "GraduationCap", label: "Educação" },
  { name: "Heart", label: "Saúde / Bem-estar" },
  { name: "Stethoscope", label: "Saúde" },
  { name: "Gem", label: "Joia / Luxo" },
  { name: "ShoppingBag", label: "Compras" },
  { name: "Music", label: "Música / Evento" },
  { name: "Camera", label: "Fotografia" },
  { name: "Mountain", label: "Montanha / Aventura" },
  { name: "Sailboat", label: "Barco / Vela" },
  { name: "Warehouse", label: "Galpão / Logística" },
  { name: "Dumbbell", label: "Esporte" },
  { name: "Sparkles", label: "Destaque" },
  { name: "Tag", label: "Genérico" },
];

export function getIconByName(name: string): LucideIcon {
  return ICON_MAP[name] || Tag;
}

export const CATEGORIA_CORES = [
  { name: "blue", label: "Azul", class: "cat-blue" },
  { name: "green", label: "Verde", class: "cat-green" },
  { name: "purple", label: "Roxo", class: "cat-purple" },
  { name: "orange", label: "Laranja", class: "cat-orange" },
  { name: "teal", label: "Verde-água", class: "cat-teal" },
  { name: "red", label: "Vermelho", class: "cat-red" },
  { name: "indigo", label: "Índigo", class: "cat-indigo" },
  { name: "cyan", label: "Ciano", class: "cat-cyan" },
  { name: "pink", label: "Rosa", class: "cat-pink" },
  { name: "amber", label: "Âmbar", class: "cat-amber" },
  { name: "gray", label: "Cinza", class: "cat-gray" },
];
